### ISSUE TITLE
CROWNY EDITORIAL

### ISSUE THREAD

**Issue by P3ter-NEARWEEK** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#103]
**PHASE 1 | INITIAL SETUP**
- [ ] [Create bounty ](https://heroes.build/bounties/bounty/456)
- [x] Assign writer to job (@Kaisenbeet)
- [ ] Create banner / @frdrkhnssn 
_**NB:**_ _If a recap of a space or event there might be a banner already to pull. Check original sources and use those images if possible._

**PHASE 2 | REVIEW & EDIT**
- [ ] Draft done and submitted @Kaisenbeet 
- [ ] Draft reviewed and edited @P3ter-NEARWEEK 

**PHASE 3 | APPROVAL & PUBLISHING**
- [ ] Bounty approved 
- [ ] Twitter post published on Twitter 

**PHASE 4 | DISTRIBUTION** 
- [ ] Twitter
- [ ] CoinMarketCap 
- [ ] Nearsocial 
- [ ] Telegram 

**PHASE 5 | AMPLIFICATION**
- [ ] Twitter
- [ ] Newsletter

## 🤼‍♂️ Reviewer
@frdrkhnssn @P3ter-NEARWEEK

**Comment by P3ter-NEARWEEK** [comment]
Currently blocked - Awaiting Crowny
