### ISSUE TITLE
NEWSLETTER 155

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#108]
**PHASE 1 | AGGREGATION, DESIGN, APPROVAL**
- [ ] Create bounty
- [ ] Assign contributor

- [ ] Cover ready  @b4ltasar 
- [ ] Draft ready @Kaisenbeet
- [ ] Draft approved @P3ter-NEARWEEK
- [ ] Graphics for social media sent to ShardDog @b4ltasar

**PHASE 2 | PUBLISHING & SoMe**
- [ ] Newsletter published / MailChimp 
- [ ] Newsletter published / Web 
- [ ] Graphics for social media sent to ShardDog @b4ltasar
- [ ] Social media post (Twitter + Telegram) @b4ltasar 

**PHASE 3 | AMPLIFICATION & HIGHLIGHTS**
- [ ] Amplify on social media @frdrkhnssn 

## 🤼‍♂️  Reviewer
@P3ter-NEARWEEK

## 🔗   Important links to be included
- [ ] 
- [ ]
- [ ] 
- [ ] 
- [ ]

**BOUNTIES FOR THE BOUNTY-SECTION:**
- [ ] 
- [ ]
- [ ]
- [ ]

**Comment by Kaisenbeet** [comment]
https://us1.admin.mailchimp.com/campaigns/wizard/neapolitan?id=10406481 

Draft is ready.

- There is no particular noteworthy East Blue link, but we have East Blue news in the Alpha thread in Top News

**Comment by P3ter-NEARWEEK** [comment]
did you publish on web @Kaisenbeet ?

**Comment by Kaisenbeet** [comment]
Not yet, not received cover for issue. has not been sent in ShardDog chat as well. Already messaged Jens

**Comment by Kaisenbeet** [comment]
https://nearweek.com/newsletters/edition-155

On web
