### ISSUE TITLE
WEEKLY ALPHA POST BY AESCOBAR #3

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#115]
**PHASE 1 | INITIAL SETUP**
- [x] Create bounty 
- [x] Assign writer to job 
- [x] Create banner / @b4ltasar
_**NB:**_ _If a recap of a space or event there might be a banner already to pull. Check original sources and use those images if possible._

**PHASE 2 | REVIEW & EDIT**
- [x] Draft done
- [x] Draft reviewed and edited 

**PHASE 3 | APPROVAL & PUBLISHING**
- [x] Bounty approved 
- [x] Twitter post published on Twitter 

**PHASE 4 | DISTRIBUTION** 
- [ ] Twitter
- [ ] CoinMarketCap 
- [ ] Nearsocial 
- [ ] Telegram 

**PHASE 5 | AMPLIFICATION**
- [ ] Twitter
- [ ] Newsletter

## 🤼‍♂️ Reviewer
@b4ltasar

## 🔗   Work doc(s) / inspirational links
SPECIFIC REFERENCE FOR THIS WEEKLY POST:
https://twitter.com/NEARWEEK/status/1768569991274639723

TEMPLATE: How to make a long-form Twitterpost:
https://docs.google.com/document/d/172BefpyKj30K6K0EM0qiq2an-PnKHNgSYOBtmwvII7s/edit?usp=sharing

**Comment by b4ltasar** [comment]
This is the final outcome of https://github.com/NEARWEEK/NEARWEEK-COMMUNITY-CONTENT/issues/102

**Comment by b4ltasar** [comment]
https://github.com/NEARWEEK/NEARWEEK-COMMUNITY-CONTENT/assets/114229415/90553cf1-c628-4f09-b9c1-0bbe5f9086d6

**Comment by aescobar00** [comment]
https://docs.google.com/document/d/1D9DyHk0H60AY0jYSL6YnLF4TwC5B1-ww_VYLY_Y8HWo/edit?usp=sharing

Here is the draft @b4ltasar @Kaisenbeet @frdrkhnssn

**Comment by Kaisenbeet** [comment]
I'll edit in time for tomorrow morning @aescobar00
