### ISSUE TITLE
MODULAR BLOCKCHAINS

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#14]
**PHASE 1 | INITIAL SETUP**
- [ ] Create bounty 
- [ ] Assign writer to job / (Naomi)
- [ ] Create banner / @b4ltasar

**PHASE 2 | REVIEW & EDIT**
- [ ] Draft done
- [ ] Draft reviewed and edited 

**PHASE 3 | APPROVAL & PUBLISHING**
- [ ] Bounty approved 
- [ ] Blog published 
- [ ] All templates finalized and ready to push

**PHASE 4 | DISTRIBUTION** 
- [ ] Medium
- [ ] Twitter
- [ ] LinkedIn 
- [ ] CoinMarketCap 
- [ ] Nearsocial 
- [ ] Telegram 

**PHASE 5 | AMPLIFICATION**
- [ ] Twitter
- [ ] Newsletter

## 🤼‍♂️ Reviewer
@b4ltasar
