### ISSUE TITLE
BI-WEEKLY DEVHUB MEGATHREAD

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#16]
## 🎉   Subtasks
Format: Twitterthread

- [ ] Draft megathread @Kaisenbeet 
- [ ] Deliver thread and summary to reviewer [(DevHub)](https://t.me/devhub_nearweek) @Kaisenbeet 
- [ ] Ping DevHub to make sure they publish @frdrkhnssn 
- [ ] Thread published on DevHub Twitter (DevHub is responsible)

## 🤼‍♂️  Reviewer 
Initially: @achildhoodhero 
Finally: NEAR DevHub

**Comment by Kaisenbeet** [comment]
Sent thread to Jose. Ideally, want him to push this before 6 pm UTC+1 so that their audience can catch Illia's space.

Also, noticed that the link to the cover has not been updated.
