### ISSUE TITLE
NEWSLETTER 138

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#20]
**PHASE 1 | AGGREGATION, DESIGN, APPROVAL**
- [ ] Cover ready  @b4ltasar 
- [ ] Draft ready @Kaisenbeet
- [ ] Draft approved @P3ter-NEARWEEK
- [ ] Graphics for social media sent to ShardDog @b4ltasar

**PHASE 2 | PUBLISHING & SoMe**
- [ ] Newsletter published / MailChimp 
- [ ] Newsletter published / Web 
- [ ] Graphics for social media sent to ShardDog @b4ltasar
- [ ] Social media post (Twitter + Telegram) @b4ltasar 

**PHASE 3 | AMPLIFICATION & HIGHLIGHTS**
- [ ] Amplify on social media @frdrkhnssn 

## 🤼‍♂️  Reviewer
@P3ter-NEARWEEK

## 🔗   Important links to be included
- [ ] 
- [ ]
- [ ] 
- [ ] 
- [ ]

**BOUNTIES FOR THE BOUNTY-SECTION:**
- [ ] 
- [ ]
- [ ]
- [ ]

**Comment by Kaisenbeet** [comment]
Newsletter draft is ready, all that is left is 
- Update stats
