### ISSUE TITLE
NEWSLETTER 139

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#21]
**PHASE 1 | AGGREGATION, DESIGN, APPROVAL**
- [ ] Cover ready  @b4ltasar 
- [ ] Draft ready @Kaisenbeet
- [ ] Draft approved @P3ter-NEARWEEK
- [ ] Graphics for social media sent to ShardDog @b4ltasar

**PHASE 2 | PUBLISHING & SoMe**
- [ ] Newsletter published / MailChimp 
- [ ] Newsletter published / Web 
- [ ] Graphics for social media sent to ShardDog @b4ltasar
- [ ] Social media post (Twitter + Telegram) @b4ltasar 

**PHASE 3 | AMPLIFICATION & HIGHLIGHTS**
- [ ] Amplify on social media @frdrkhnssn 

## 🤼‍♂️  Reviewer
@P3ter-NEARWEEK

## 🔗   Important links to be included
- [ ] 
- [ ]
- [ ] 
- [ ] 
- [ ]

**BOUNTIES FOR THE BOUNTY-SECTION:**
- [ ] 
- [ ]
- [ ]
- [ ]

**Comment by b4ltasar** [comment]
**BOUNTY LINK**: https://heroes.build/bounties/bounty/253

**Comment by Kaisenbeet** [comment]
Hello @P3ter-NEARWEEK @b4ltasar just a quick note on the newsletter.

i have drafted the main headlines, but I have a bit of an unexpected emergency so I'll add descriptions tomorrow Saturday. As usual, by Monday we should have the full newsletter

**Comment by Kisgus** [comment]
Gm @b4ltasar @Kaisenbeet we also need to include upcoming NEAR events in the buttom "GETTING ONBOARDED TO NEAR" section, the green events that needs to be included are:

Crypto Finance Conference
Eth Denver
BUIDL Asia

Also include a section regarding virtual events and link to https://nearweek.com/calendar

**Comment by Kaisenbeet** [comment]
#140 preview ready. Test emails have been sent

https://us1.admin.mailchimp.com/campaigns/edit?id=10394566

**Comment by Kaisenbeet** [comment]
I took the liberty of adding links to the events

**Comment by Kaisenbeet** [comment]
Newsletter draft already up on Strapi. Awaiting small sized cover to add @b4ltasar

**Comment by Kaisenbeet** [comment]
Newsletter published on web. 

https://nearweek.com/newsletters/edition-140
