### ISSUE TITLE
NEWSLETTER 141

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#27]
**PHASE 1 | AGGREGATION, DESIGN, APPROVAL**
- [ ] Cover ready  @b4ltasar 
- [ ] Draft ready @Kaisenbeet
- [ ] Draft approved @P3ter-NEARWEEK
- [ ] Graphics for social media sent to ShardDog @b4ltasar

**PHASE 2 | PUBLISHING & SoMe**
- [ ] Newsletter published / MailChimp 
- [ ] Newsletter published / Web 
- [ ] Graphics for social media sent to ShardDog @b4ltasar
- [ ] Social media post (Twitter + Telegram) @b4ltasar 

**PHASE 3 | AMPLIFICATION & HIGHLIGHTS**
- [ ] Amplify on social media @frdrkhnssn 

## 🤼‍♂️  Reviewer
@P3ter-NEARWEEK

## 🔗   Important links to be included
- [ ] 
- [ ]
- [ ] 
- [ ] 
- [ ]

**BOUNTIES FOR THE BOUNTY-SECTION:**
- [ ] 
- [ ]
- [ ]
- [ ]

**Comment by b4ltasar** [comment]
**BOUNTY LINK:** https://heroes.build/bounties/bounty/254
