### ISSUE TITLE
NEWSLETTER 143

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#30]
**PHASE 1 | AGGREGATION, DESIGN, APPROVAL**
- [x] Create bounty
- [x] Assign contributor

- [x] Cover ready  @b4ltasar 
- [x] Draft ready @Kaisenbeet
- [x] Draft approved @P3ter-NEARWEEK
- [x] Graphics for social media sent to ShardDog @b4ltasar

**PHASE 2 | PUBLISHING & SoMe**
- [x] Newsletter published / MailChimp 
- [x] Newsletter published / Web 
- [x] Graphics for social media sent to ShardDog @b4ltasar
- [x] Social media post (Twitter + Telegram) @b4ltasar 

**PHASE 3 | AMPLIFICATION & HIGHLIGHTS**
- [x] Amplify on social media @frdrkhnssn 

## 🤼‍♂️  Reviewer
@P3ter-NEARWEEK

## 🔗   Important links to be included
- [x] https://twitter.com/ilblackdragon/status/1744672594005999779
- [x] https://twitter.com/CFCstmoritz/status/1745148436247089515
- [ ] https://twitter.com/hosseeb/status/1744594500230746173
- [x] https://twitter.com/nekotoken_xyz/status/1745356602583261287
- [x] https://twitter.com/pikespeak_ai/status/1745141739050963121
- [ ] https://twitter.com/NEARWEEK/status/1745035848796516404
- [ ] https://twitter.com/neardc/status/1743817020553232802
- [x] https://twitter.com/here_wallet/status/1745068281902325982
- [x] https://twitter.com/ilblackdragon/status/1743942217947857032
- [x] https://twitter.com/NEARDevHub/status/1744413783747936504
- [ ] https://twitter.com/Banyan_NEAR/status/1744372715551666624
- [x] Permanent link going fwd: https://twitter.com/nekotoken_xyz/status/1740469476410429803

**BOUNTIES FOR THE BOUNTY-SECTION:**
- [ ] 
- [ ]
- [ ]
- [ ]

**Comment by b4ltasar** [comment]
Illia announcing sharding phase ll is in production Will be featured on magazine cover

**Comment by Kaisenbeet** [comment]
**Initial outline draft of newsletter** :
https://us1.admin.mailchimp.com/campaigns/wizard/neapolitan?id=10397110


**[TO BE DONE]** over weekend
- IN OTHER NEWS section
- Complete descriptions in ECOSYSTEM section
- Introduction - will focus it on the announcement from NF on internal changes
- Edit and refine overall


Newsletter will be ready before review at 10 AM on Monday.

PS: As always news is always incoming. As we saw last Monday and many times in the past, some news can come in on Monday before we publish. Will always maintain a flexible approach in trying to update newsletter.

**Comment by Kaisenbeet** [comment]
Newsletter draft done and test emails sent out.

Regarding links to be included, see some thoughts below:

- Thanks for the links, most of them were already on course to be in the newsletter
- The NDC grassroots funding news was in last week's newsletter (Ecosystem section)
- The Chain abstraction hackathon news from Banyan was in last week's newsletter (Dev section)
- Personally feel adding the megathread to the newsletter is a bit redundant given that it is a summary of news we already published in newsletter issues and have it all over socials, the website and daily newsletter. 
- I think given the length of the newsletter this week, we can add Hosseeb's link to next week's newsletter
