### ISSUE TITLE
NEWSLETTER 144

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#31]
**PHASE 1 | AGGREGATION, DESIGN, APPROVAL**
- [ ] Create bounty
- [x] Assign contributor

- [x] Cover ready  @b4ltasar 
- [x] Draft ready @Kaisenbeet
- [x] Draft approved @P3ter-NEARWEEK
- [x] Graphics for social media sent to ShardDog @b4ltasar

**PHASE 2 | PUBLISHING & SoMe**
- [x] Newsletter published / MailChimp 
- [x] Newsletter published / Web 
- [x] Graphics for social media sent to ShardDog @b4ltasar
- [x] Social media post (Twitter + Telegram) @b4ltasar 

**PHASE 3 | AMPLIFICATION & HIGHLIGHTS**
- [x] Amplify on social media @frdrkhnssn 

## 🤼‍♂️  Reviewer
@P3ter-NEARWEEK

## 🔗   Important links to be included
- [x] **[Rogues Studio seeking Head of Marketing (part-time contract) to lead marketing efforts with a strong focus on player acquisition and growth marketing.](https://wellfound.com/l/2zR9PX )**  FOR THE JOB SECTION

- [ ] https://twitter.com/sandeepnailwal/status/1748071918027034784 + https://twitter.com/ilblackdragon/status/1748118149537431605
- [x] https://twitter.com/NEARProtocol/status/1747302751879479572
- [x] https://twitter.com/lavanetxyz/status/1747653696476099017
- [x] https://twitter.com/sharddog/status/1747995337745186991
- [x] https://twitter.com/ilblackdragon/status/1747648984057807147
- [x] https://twitter.com/MeteorWallet/status/1746951179089727552
- [ ] https://twitter.com/jassification/status/1746898419229360457 
- [x] https://twitter.com/NEARProtocol/status/1747636096446476708
- [x] https://twitter.com/caseykcaruso/status/1747266612405871031
- [x] https://twitter.com/LinearProtocol/status/17474884558804829584
- [x] https://twitter.com/urbit/status/1747362589103808747 + https://twitter.com/NEARProtocol/status/1748027724172558492
- [ ] https://twitter.com/SweatEconomy/status/1747974627790393847
- [x] https://twitter.com/OpenForest_/status/1747699751569809737
- [x] https://twitter.com/neardc/status/1746160255300473108
- [x] https://twitter.com/joespano_/status/1747731407638499728
- [x] https://twitter.com/meta_pool/status/1747989677825475013 + https://twitter.com/meta_pool/status/1747398785473335558
- [x] https://twitter.com/SweatEconomy/status/1747615942811455546
- [ ] https://twitter.com/JumpDeFi/status/1747850451892998542
- [x] https://twitter.com/finance_ref/status/1747578526121750982
- [ ] https://twitter.com/finance_ref/status/1746815303537856974
- [x] https://twitter.com/BowenWang18/status/1747313487066562866
- [x] https://twitter.com/jassification/status/1747564751683743856

**BOUNTIES FOR THE BOUNTY-SECTION:**
- [ ] 
- [ ]
- [ ]
- [ ]

**Comment by Kaisenbeet** [comment]
initial draft of newsletter with headlines is ready.

**[TO DO] over weekend**
- Add descriptions
- Write introduction (intro will celebrate NEARWEEK and ShardDOg for reaching new "k" milestones, which underlines their impact/value on ecosystem)
- Update "IN OTHER NEWS" section

https://us1.admin.mailchimp.com/campaigns/wizard/neapolitan?id=10398414

**Comment by Kaisenbeet** [comment]
https://twitter.com/neardc/status/1746160255300473108 - Was in newsletter #142

https://twitter.com/sandeepnailwal/status/1748071918027034784 + https://twitter.com/ilblackdragon/status/1748118149537431605 -  Will be put in Dev megathread

**Comment by Kaisenbeet** [comment]
https://nearweek.com/newsletters/edition-144
