### ISSUE TITLE
NEWSLETTER 145

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#32]
**PHASE 1 | AGGREGATION, DESIGN, APPROVAL**
- [ ] Create bounty
- [ ] Assign contributor

- [ ] Cover ready  @b4ltasar 
- [ ] Draft ready @Kaisenbeet
- [ ] Draft approved @P3ter-NEARWEEK
- [ ] Graphics for social media sent to ShardDog @b4ltasar

**PHASE 2 | PUBLISHING & SoMe**
- [ ] Newsletter published / MailChimp 
- [ ] Newsletter published / Web 
- [ ] Graphics for social media sent to ShardDog @b4ltasar
- [ ] Social media post (Twitter + Telegram) @b4ltasar 

**PHASE 3 | AMPLIFICATION & HIGHLIGHTS**
- [ ] Amplify on social media @frdrkhnssn 

## 🤼‍♂️  Reviewer
@P3ter-NEARWEEK

## 🔗   Important links to be included
- [ ] 
- [ ]
- [ ] 
- [ ] 
- [ ]

**BOUNTIES FOR THE BOUNTY-SECTION:**
- [ ] 
- [ ]
- [ ]
- [ ]

**Comment by Kaisenbeet** [comment]
@b4ltasar initial draft of newsletter ready

https://us1.admin.mailchimp.com/campaigns/wizard/neapolitan?id=10399162


**[TO BE DONE]** - over weekend
- Add all descriptions
- Update intro
-Update "IN OTHER NEWS" section
- Final edit and link check

**Comment by Kaisenbeet** [comment]
Newsletter Update

- Final draft ready, updated to reflect news shared over weekend and this morning until 9AM UTC+1
- Test emails sent

**Comment by Kaisenbeet** [comment]
Newsletter published on web

https://nearweek.com/newsletters/edition-145
