### ISSUE TITLE
RECAP MONTHLY DEVHUB SPACE / JANUARY

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#35]
**PHASE 1 | INITIAL SETUP**
- [x] Create bounty 
- [x] Assign writer to job 
- [x] Create banner / @b4ltasar
_**NB:**_ _If a recap of a space or event there might be a banner already to pull. Check original sources and use those images if possible._

**PHASE 2 | REVIEW & EDIT**
- [x] Draft done
- [x] Draft reviewed and edited 

**PHASE 3 | APPROVAL & PUBLISHING**
- [x] Bounty approved 
- [ ] Twitter post published on Twitter 

**PHASE 4 | DISTRIBUTION** 
- [x] Twitter
- [x] CoinMarketCap 
- [ ] Nearsocial 
- [x] Telegram 

**PHASE 5 | AMPLIFICATION**
- [x] Twitter
- [ ] Newsletter

## 🤼‍♂️ Reviewer
@b4ltasar

## 🔗   Work doc(s) / inspirational links
TEMPLATE: How to make a long-form Twitterpost:
https://docs.google.com/document/d/172BefpyKj30K6K0EM0qiq2an-PnKHNgSYOBtmwvII7s/edit?usp=sharing

**Comment by Kaisenbeet** [comment]
Recap draft

https://typefully.com/t/w8NDQqY

**Comment by Kaisenbeet** [comment]
Been trying to add these two graphics, one giving an overview of HackBox and the other for Chain Abstraction Day, but not been able. 

I can add them on my personal Typefully but when I transfer to the NEARWEEK Typefully it refuses to add them
![Uploading Chain abstraction.jpeg…]()

**Comment by Kaisenbeet** [comment]
![HackBox](https://github.com/NEARWEEK/NEARWEEK-COMMUNITY-CONTENT/assets/146084459/386da29f-4a57-4329-9fbd-e16d68f6e612)

**Comment by b4ltasar** [comment]
Published on Twitter, Telegram, CMC

**Comment by b4ltasar** [comment]
Tweet: https://x.com/NEARWEEK/status/1755581923915620628?s=20
