### ISSUE TITLE
MONTHLY DEFI SPACE / JANUARY

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#37]
**PHASE 1 | PRELIMINIARY PLANNING** 
- [x] Lock date/time
- [x] Find host
- [ ] Create space

**PHASE 2 | EXTENDED DETAILS & INVITATIONS** 
- [x] Create Telegram Group
- [x] Send the agenda in the Telegram Group
- [ ] Find Guests
Guests for this space are: 

- [x] Invite all guests to calendar event
- Include twitterspace link
- Tell everyone to join from their respective project profiles

**PHASE 3 | DESIGN & PROMOTION**
- [x] Create banner
- [x] Announce space on Twitter  (min. 4 days before)
- [x] Promote on Telegram 
- [x] Include in daily newsletter 

**PHASE 4 | FINAL EXECUTION**
- [x] Host space from NW Twitter

**PHASE 5 | POST DELIVERABLES:**
- [x] Upload space to web + Spotify
- [x] Amplification on Social Media

_**NB**_
**Is this gonna be a recap thread?**
**Do we need to include any content around this space in the upcoming newsletter?** 
(if so add important links to the respective newsletter issue)

## 🤼‍♂️ Reviewer
@b4ltasar

## 🔗  Important links
Twitterspace link:
Calendar invite:
Telegram group:
Agenda:
Twitter post:
