### ISSUE TITLE
MONTHLY DEVHUB SPACE / JANUARY

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#38]
**PHASE 1 | PRELIMINIARY PLANNING** 
- [ ] Lock date/time
- [ ] Find host
- [ ] Create space

**PHASE 2 | EXTENDED DETAILS & INVITATIONS** 
- [ ] Create Telegram Group
- [ ] Send the agenda in the Telegram Group
- [ ] Find Guests
Guests for this space are: 

- [ ] Invite all guests to calendar event
- Include twitterspace link
- Tell everyone to join from their respective project profiles

**PHASE 3 | DESIGN & PROMOTION**
- [ ] Create banner
- [ ] Announce space on Twitter  (min. 4 days before)
- [ ] Promote on Telegram 
- [ ] Include in daily newsletter 

**PHASE 4 | FINAL EXECUTION**
- [ ] Host space from NW Twitter

**PHASE 5 | POST DELIVERABLES:**
- [ ] Upload space to web + Spotify
- [ ] Amplification on Social Media

_**NB**_
**Is this gonna be a recap thread?**
**Do we need to include any content around this space in the upcoming newsletter?** 
(if so add important links to the respective newsletter issue)

## 🤼‍♂️ Reviewer
@b4ltasar

## 🔗  Important links
Twitterspace link:
Calendar invite:
Telegram group:
Agenda:
Twitter post:

**Comment by b4ltasar** [comment]
Postponed to 31st of January
