### ISSUE TITLE
WHAT IS NEAR? BEST RESOURCES TO LEARN ABOUT: DATA AVAILABILITY ON NEAR

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#39]
**PHASE 1 | INITIAL SETUP**
- [x] Create bounty 
- [x] Assign writer to job 
- [ ] Create banner / @b4ltasar
_**NB:**_ _If a recap of a space or event there might be a banner already to pull. Check original sources and use those images if possible._

**PHASE 2 | REVIEW & EDIT**
- [ ] Draft done
- [ ] Draft reviewed and edited 

**PHASE 3 | APPROVAL & PUBLISHING**
- [ ] Bounty approved 
- [ ] Twitter post published on Twitter 

**PHASE 4 | DISTRIBUTION** 
- [ ] Twitter
- [ ] CoinMarketCap 
- [ ] Nearsocial 
- [ ] Telegram 

**PHASE 5 | AMPLIFICATION**
- [ ] Twitter
- [ ] Newsletter

## 🤼‍♂️ Reviewer
@b4ltasar

## 🔗   Work doc(s) / inspirational links
TEMPLATE: How to make a long-form Twitterpost:
https://docs.google.com/document/d/172BefpyKj30K6K0EM0qiq2an-PnKHNgSYOBtmwvII7s/edit?usp=sharing

**Comment by b4ltasar** [comment]
No writer needed as internal task. @P3ter-NEARWEEK is the writer
