### ISSUE TITLE
NEWSLETTER 147

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#48]
**PHASE 1 | AGGREGATION, DESIGN, APPROVAL**
- [x] Create bounty
- [x] Assign contributor

- [x] Cover ready  @b4ltasar 
- [x] Draft ready @Kaisenbeet
- [x] Draft approved @P3ter-NEARWEEK
- [x] Graphics for social media sent to ShardDog @b4ltasar

**PHASE 2 | PUBLISHING & SoMe**
- [x] Newsletter published / MailChimp 
- [x] Newsletter published / Web 
- [x] Graphics for social media sent to ShardDog @b4ltasar
- [x] Social media post (Twitter + Telegram) @b4ltasar 

**PHASE 3 | AMPLIFICATION & HIGHLIGHTS**
- [x] Amplify on social media @frdrkhnssn 

## 🤼‍♂️  Reviewer
@P3ter-NEARWEEK

## 🔗   Important links to be included
- [ ] 
- [ ]
- [ ] 
- [ ] 
- [ ]

**BOUNTIES FOR THE BOUNTY-SECTION:**
- [ ] 
- [ ]
- [ ]
- [ ]

**Comment by Kaisenbeet** [comment]
Initial newsletter draft headlines ready

https://us1.admin.mailchimp.com/campaigns/wizard/neapolitan?id=10400586# 


**Few notes**
- Dev news a little thin (3 right now), keeping an eye out for new updates
- I always update "IN OTHER NEWS" section on Sunday evening/Monday mornings because fresh versions of the newsletters are follow always go out then with more recent news
- Adding descriptions later today, through Saturday

**Comment by Kaisenbeet** [comment]
Final draft ready.
