### ISSUE TITLE
NEWSLETTER 149

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#50]
**PHASE 1 | AGGREGATION, DESIGN, APPROVAL**
- [x] Create bounty
- [x] Assign contributor

- [x] Cover ready  @b4ltasar 
- [x] Draft ready @Kaisenbeet
- [x] Draft approved @P3ter-NEARWEEK
- [x] Graphics for social media sent to ShardDog @b4ltasar

**PHASE 2 | PUBLISHING & SoMe**
- [x] Newsletter published / MailChimp 
- [x] Newsletter published / Web 
- [x] Graphics for social media sent to ShardDog @b4ltasar
- [x] Social media post (Twitter + Telegram) @b4ltasar 

**PHASE 3 | AMPLIFICATION & HIGHLIGHTS**
- [x] Amplify on social media @frdrkhnssn 

## 🤼‍♂️  Reviewer
@P3ter-NEARWEEK

## 🔗   Important links to be included
- [x] https://x.com/finance_ref/status/1760650653309796413?s=20
- [ ]
- [ ] 
- [ ] 
- [ ]

**BOUNTIES FOR THE BOUNTY-SECTION:**
- [ ] 
- [ ]
- [ ]
- [ ]
