### ISSUE TITLE
NEWSLETTER 150

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#51]
**PHASE 1 | AGGREGATION, DESIGN, APPROVAL**
- [x] Create bounty
- [x] Assign contributor

- [x] Cover ready  @b4ltasar 
- [x] Draft ready @Kaisenbeet
- [x] Draft approved @P3ter-NEARWEEK
- [x] Graphics for social media sent to ShardDog @b4ltasar

**PHASE 2 | PUBLISHING & SoMe**
- [x] Newsletter published / MailChimp 
- [x] Newsletter published / Web 
- [x] Graphics for social media sent to ShardDog @b4ltasar
- [x] Social media post (Twitter + Telegram) @b4ltasar 

**PHASE 3 | AMPLIFICATION & HIGHLIGHTS**
- [x] Amplify on social media @frdrkhnssn 

## 🤼‍♂️  Reviewer
@P3ter-NEARWEEK

## 🔗   Important links to be included
- [ ] 
- [ ]
- [ ] 
- [ ] 
- [ ]

**BOUNTIES FOR THE BOUNTY-SECTION:**
- [ ] 
- [ ]
- [ ]
- [ ]

**Comment by b4ltasar** [comment]
BOUNTY LINK: https://heroes.build/bounties/bounty/438

**Comment by Kaisenbeet** [comment]
Initial draft 

https://us1.admin.mailchimp.com/campaigns/wizard/neapolitan?id=10402598
