### ISSUE TITLE
RECAP MONTHLY DEFI SPACE / FEBRUARY

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#59]
**PHASE 1 | INITIAL SETUP**
- [x] Create bounty 
- [x] Assign writer to job 
- [x] Create banner / @b4ltasar
_**NB:**_ _If a recap of a space or event there might be a banner already to pull. Check original sources and use those images if possible._

**PHASE 2 | REVIEW & EDIT**
- [x] Draft done
- [x] Draft reviewed and edited 

**PHASE 3 | APPROVAL & PUBLISHING**
- [x] Bounty approved 
- [x] Twitter post published on Twitter 

**PHASE 4 | DISTRIBUTION** 
- [x] Twitter
- [ ] CoinMarketCap 
- [ ] Nearsocial 
- [ ] Telegram 

**PHASE 5 | AMPLIFICATION**
- [x] Twitter
- [x] Newsletter

## 🤼‍♂️ Reviewer
@b4ltasar

## 🔗   Work doc(s) / inspirational links
TEMPLATE: How to make a long-form Twitterpost:
https://docs.google.com/document/d/172BefpyKj30K6K0EM0qiq2an-PnKHNgSYOBtmwvII7s/edit?usp=sharing

**Comment by b4ltasar** [comment]
BOUNTY LINK: https://heroes.build/bounties/bounty/409

**Comment by Kaisenbeet** [comment]
Recap draft

https://typefully.com/t/IqsJXVm  

- Illia's talk on Chain Signatures has not yet been published so I referenced the chain abstraction demo by oleg from Sweatcoin instead
