### ISSUE TITLE
NAOMI BLOGPOST #1 / MAR (zkWasm)

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#67]
**PHASE 1 | INITIAL SETUP**
- [ ] Create bounty 
- [x] Assign writer to job (naomi)
- [x] Create banner / @b4ltasar

**PHASE 2 | REVIEW & EDIT**
- [x] Draft done
- [x] Draft reviewed and edited 

**PHASE 3 | APPROVAL & PUBLISHING**
- [ ] Bounty approved 
- [x] Blog published 
- [ ] All templates finalized and ready to push

**PHASE 4 | DISTRIBUTION** 
- [x] Medium
- [x] Twitter
- [x] LinkedIn 
- [ ] CoinMarketCap 
- [ ] Nearsocial 
- [ ] Telegram 

**PHASE 5 | AMPLIFICATION**
- [x] Twitter
- [x] Newsletter

**Comment by b4ltasar** [comment]
Tentative dates. week numbers are absolute

**Comment by b4ltasar** [comment]
Hard to find information about execution layer for Naomi to write about. If we didn't get any information from core partners and relevant bases before end of week postpone topic and adjust

**Comment by b4ltasar** [comment]
BOUNTY LINK: https://heroes.build/bounties/bounty/412
