### ISSUE TITLE
BLOGPOST #1 / MARCH

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#69]
**PHASE 1 | INITIAL SETUP**
- [ ] Create bounty 
- [ ] Assign writer to job (naomi)
- [ ] Create banner / @b4ltasar

**PHASE 2 | REVIEW & EDIT**
- [ ] Draft done
- [ ] Draft reviewed and edited 

**PHASE 3 | APPROVAL & PUBLISHING**
- [ ] Bounty approved 
- [ ] Blog published 
- [ ] All templates finalized and ready to push

**PHASE 4 | DISTRIBUTION** 
- [ ] Medium
- [ ] Twitter
- [ ] LinkedIn 
- [ ] CoinMarketCap 
- [ ] Nearsocial 
- [ ] Telegram 

**PHASE 5 | AMPLIFICATION**
- [ ] Twitter
- [ ] Newsletter

**Comment by b4ltasar** [comment]
Tentative dates. week numbers are absolute
