### ISSUE TITLE
BLOGPOST #2 / MARCH

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#70]
**PHASE 1 | INITIAL SETUP**
- [ ] Create bounty 
- [ ] Assign writer to job (naomi)
- [ ] Create banner / @b4ltasar

**PHASE 2 | REVIEW & EDIT**
- [ ] Draft done
- [ ] Draft reviewed and edited 

**PHASE 3 | APPROVAL & PUBLISHING**
- [ ] Bounty approved 
- [ ] Blog published 
- [ ] All templates finalized and ready to push

**PHASE 4 | DISTRIBUTION** 
- [ ] Medium
- [ ] Twitter
- [ ] LinkedIn 
- [ ] CoinMarketCap 
- [ ] Nearsocial 
- [ ] Telegram 

**PHASE 5 | AMPLIFICATION**
- [ ] Twitter
- [ ] Newsletter

**Comment by b4ltasar** [comment]
Tentative dates. week numbers are absolute

**Comment by b4ltasar** [comment]
![Image](https://github.com/NEARWEEK/NEARWEEK-COMMUNITY-CONTENT/assets/114229415/0f594d39-a9a7-46b8-b922-e479194f0cf1)

**Comment by b4ltasar** [comment]
Draftlink: https://medium.com/p/67ca04299890/edit
