### ISSUE TITLE
MONTHLY MOST EXCITING NEWS ON NEAR IN FEBRUARY

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#85]
**PHASE 1 | INITIAL SETUP**
- [ ] Assign writer to job 
- [ ] Create banner / @b4ltasar

**PHASE 2 | REVIEW & EDIT**
- [ ] Draft done
- [ ] Draft reviewed and edited 

**PHASE 3 | PUBLISHING**
- [ ] Twitter post published on Twitter 

**PHASE 4 | DISTRIBUTION** 
- [ ] Twitter
- [ ] CoinMarketCap 
- [ ] Nearsocial 
- [ ] Telegram 

**PHASE 5 | AMPLIFICATION**
- [ ] Twitter
- [ ] Newsletter

## 🤼‍♂️ Reviewer
@b4ltasar

**Comment by b4ltasar** [comment]
![Image](https://github.com/NEARWEEK/NEARWEEK-COMMUNITY-CONTENT/assets/114229415/7e28a986-6d92-4315-b895-2c081c02e4db)
