### ISSUE TITLE
MONTHLY MOST EXCITING NEWS ON NEAR IN MARCH

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#86]
**PHASE 1 | INITIAL SETUP**
- [x] Assign writer to job 
- [x] Create banner / @b4ltasar

**PHASE 2 | REVIEW & EDIT**
- [x] Draft done
- [x] Draft reviewed and edited 

**PHASE 3 | PUBLISHING**
- [x] Twitter post published on Twitter 

**PHASE 4 | DISTRIBUTION** 
- [ ] Twitter
- [ ] CoinMarketCap 
- [ ] Nearsocial 
- [ ] Telegram 

**PHASE 5 | AMPLIFICATION**
- [ ] Twitter
- [ ] Newsletter

## 🤼‍♂️ Reviewer
@b4ltasar

**Comment by b4ltasar** [comment]
![Image](https://github.com/NEARWEEK/NEARWEEK-COMMUNITY-CONTENT/assets/114229415/ebc271af-cf9c-493e-a6e4-6742726e1186)

**Comment by b4ltasar** [comment]
https://x.com/NEARWEEK/status/1775847488186151067?s=20
