### ISSUE TITLE
WRITE A THREAD ABOUT CHAIN ABSTRACTION ON NEAR

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#89]
**PHASE 1 | INITIAL SETUP**
- [ ] Create twitterpost and schedule in Typefully
- [ ] Create banner / @b4ltasar
- [ ] Create bounty (if necessary)

**PHASE 2 | PUBLISHING**
- [ ] Twitter contest published on Twitter 

**PHASE 4 | PICK WINNERS & REWARD** 
- [ ] Pick winners & get their nearwallets
- [ ] add nearwallets to bounty
- [ ] Finalize bounty

**BOUNTY LINK:**
🔗

**Comment by b4ltasar** [comment]
![Image](https://github.com/NEARWEEK/NEARWEEK-COMMUNITY-CONTENT/assets/114229415/cb9848e0-1307-4f51-94a1-74fd839938ce)

**Comment by b4ltasar** [comment]
BOUNTY LINK: https://heroes.build/bounties/bounty/433
