### ISSUE TITLE
WRITE A THREAD ABOUT AI & NEAR

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#90]
**PHASE 1 | INITIAL SETUP**
- [ ] Create twitterpost and schedule in Typefully
- [ ] Create banner / @b4ltasar
- [ ] Create bounty (if necessary)

**PHASE 2 | PUBLISHING**
- [ ] Twitter contest published on Twitter 

**PHASE 4 | PICK WINNERS & REWARD** 
- [ ] Pick winners & get their nearwallets
- [ ] add nearwallets to bounty
- [ ] Finalize bounty

**BOUNTY LINK:**
🔗

**Comment by b4ltasar** [comment]
![Image](https://github.com/NEARWEEK/NEARWEEK-COMMUNITY-CONTENT/assets/114229415/8f62fcb3-0b9f-4e36-8050-6defff8e1ef2)

**Comment by b4ltasar** [comment]
Scheduled to go live monday 25th via Typefully at 12:00 CET.
**_Please remember to include in newsletter._**

Typefully link: https://typefully.com/t/QuDSCl4

**Comment by b4ltasar** [comment]
BOUNTY LINK: https://heroes.build/bounties/bounty/429
