### ISSUE TITLE
HOW TO FIND DAPPS & RESOURCES

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#92]
**PHASE 1 | INITIAL SETUP**
- [x] Assign writer to job / Yuen
- [x] Create banner / @b4ltasar

**PHASE 2 | REVIEW & EDIT**
- [ ] Draft done
- [ ] Draft reviewed and edited 

**PHASE 3 | PUBLISHING**
- [ ] Twitter post published on Twitter 

**PHASE 4 | DISTRIBUTION** 
- [ ] Twitter
- [ ] CoinMarketCap 
- [ ] Nearsocial 
- [ ] Telegram 

**PHASE 5 | AMPLIFICATION**
- [ ] Twitter
- [ ] Newsletter

**Comment by b4ltasar** [comment]
![Image](https://github.com/NEARWEEK/NEARWEEK-COMMUNITY-CONTENT/assets/114229415/1f6b1d4b-ce12-45ba-8de1-1fe637679ce1)

**Comment by YuenNft** [comment]
https://typefully.com/t/IoPrqj0
