### ISSUE TITLE
HOW TO FIND SPACES & EVENTS

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#95]
**PHASE 1 | INITIAL SETUP**
- [ ] Assign writer to job 
- [ ] Create banner / @b4ltasar

**PHASE 2 | REVIEW & EDIT**
- [ ] Draft done
- [ ] Draft reviewed and edited 

**PHASE 3 | PUBLISHING**
- [ ] Twitter post published on Twitter 

**PHASE 4 | DISTRIBUTION** 
- [ ] Twitter
- [ ] CoinMarketCap 
- [ ] Nearsocial 
- [ ] Telegram 

**PHASE 5 | AMPLIFICATION**
- [ ] Twitter
- [ ] Newsletter

**Comment by b4ltasar** [comment]
![Image](https://github.com/NEARWEEK/NEARWEEK-COMMUNITY-CONTENT/assets/114229415/b4707fb7-ce64-41aa-8002-1e3511ec34ec)
