### ISSUE TITLE
EAST BLUE

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#96]
**PHASE 1 | INITIAL SETUP**
- [x] Create bounty 
- [x] Assign writer to job 
- [x] Create banner / @b4ltasar
_**NB:**_ _If a recap of a space or event there might be a banner already to pull. Check original sources and use those images if possible._

**PHASE 2 | REVIEW & EDIT**
- [x] [Draft done and submitted to Typefully](https://typefully.com/t/riFHg2V)
- [x] Draft reviewed and edited 

**PHASE 3 | APPROVAL & PUBLISHING**
- [x] Bounty approved 
- [x] Twitter post published on Twitter 

**PHASE 4 | DISTRIBUTION** 
- [x] Twitter
- [ ] CoinMarketCap 
- [ ] Nearsocial 
- [ ] Telegram 

**PHASE 5 | AMPLIFICATION**
- [x] Twitter
- [ ] Newsletter

## 🤼‍♂️ Reviewer
@frdrkhnssn

**Comment by b4ltasar** [comment]
BOUNTY LINK:
https://heroes.build/bounties/bounty/437

**Comment by b4ltasar** [comment]
@P3ter-NEARWEEK & @Kaisenbeet what did you agree on this task in terms of deadlines and SoMe push?
