### ISSUE TITLE
AI & NEAR PROTOCOL

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#97]
**PHASE 1 | INITIAL SETUP**
- [x] Create bounty 
- [x] Assign writer to job / DJ PANGBURN
- [x] Create banner / @b4ltasar

**PHASE 2 | REVIEW & EDIT**
- [ ] Draft done
- [ ] Draft reviewed and edited 

**PHASE 3 | APPROVAL & PUBLISHING**
- [ ] Bounty approved 
- [ ] Blog published 
- [ ] All templates finalized and ready to push

**PHASE 4 | DISTRIBUTION** 
- [ ] Medium
- [ ] Twitter
- [ ] LinkedIn 
- [ ] CoinMarketCap 
- [ ] Nearsocial 
- [ ] Telegram 

**PHASE 5 | AMPLIFICATION**
- [ ] Twitter
- [ ] Newsletter

**Comment by b4ltasar** [comment]
BOUNTY LINK: https://heroes.build/bounties/bounty/435

**Comment by b4ltasar** [comment]
![Image](https://github.com/NEARWEEK/NEARWEEK-COMMUNITY-CONTENT/assets/114229415/a672e1a8-dadb-4919-b431-f11da5fd4ecc)

**Comment by b4ltasar** [comment]
Close as too much overdue and now irrelevant for now
